# Generated by Django 5.2.5 on 2025-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_created_at_product_is_sold_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttip',
            name='is_poisoned',
            field=models.BooleanField(default=False),
        ),
    ]
