# Generated by Django 5.2.5 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productknowledgebase_ragchatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Product specifications in JSON format'),
        ),
    ]
