# Generated by Django 5.2.5 on 2025-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_detailed_description_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productknowledgebase',
            name='category',
            field=models.CharField(choices=[('product_info', 'Product Information'), ('features', 'Product Features'), ('usage', 'Usage & Applications'), ('care_instructions', 'Care & Maintenance'), ('specifications', 'Technical Specifications')], max_length=100),
        ),
    ]
