# Generated by Django 5.2.5 on 2025-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_update_knowledge_base_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragchatsession',
            name='model_used',
            field=models.CharField(default='mistral', help_text='LLM model used for this chat session', max_length=100),
        ),
    ]
