# Generated by Django 5.2.5 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_update_model_used_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttip',
            name='is_poisoned',
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('customers', 'Customers Only'), ('staff', 'Staff Only'), ('admin', 'Admin Only')], default='all', help_text='Who can use this coupon', max_length=10),
        ),
    ]
