"""Record the defense-level golden baseline (T002).

Captures the DECISION SURFACE of the defense pipeline for a fixed payload corpus
at levels 0, 1 and 2, so a later refactor can be proven not to change behaviour.

It deliberately does not record rendered model replies. At level 2 the NeMo rail
calls an LLM and fails open when the package is absent, so a reply diff would be
non-deterministic and would record "L2 did nothing" in CI.

Run with:  python -m scripts.record_defense_golden
Determinism: running twice must produce no git diff.
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
import sys

if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from app.core.config import get_settings
from app.defense.intent_classifier import CONFIDENCE_FULL_MATCH_COUNT
from app.defense.output_moderator import OutputModerator
from app.defense.pipeline import defense_pipeline

GOLDEN_DIR = _ROOT / "tests" / "golden"
PAYLOADS_PATH = GOLDEN_DIR / "defense_payloads.json"
BASELINE_PATH = GOLDEN_DIR / "defense_baseline.json"

LEVELS = (0, 1, 2)


def expand(text: str) -> str:
    """Expand generated-length placeholders so the corpus file stays readable."""
    if text.startswith("__GENERATED_LEN_") and text.endswith("__"):
        length = int(text[len("__GENERATED_LEN_"):-2])
        return "x" * length
    return text


async def record() -> dict:
    settings = get_settings()
    payloads = json.loads(PAYLOADS_PATH.read_text())

    # Telemetry writes to the real aigoat.db via a background task. Silence it so
    # recording a baseline never mutates a developer's database.
    from app.defense.telemetry import TelemetryLogger

    async def _noop(self, data: dict) -> None:
        return None

    TelemetryLogger._write_to_db = _noop  # type: ignore[method-assign]

    input_rows: list[dict] = []
    for item in payloads["input"]:
        text = expand(item["text"])
        for level in LEVELS:
            result = await defense_pipeline.process_input(text, level, user_id=None)
            intent = result.intent
            input_rows.append({
                "payload_id": item["id"],
                "level": level,
                "allowed": result.allowed,
                "message": result.message,
                "intent": intent.label if intent else None,
                "confidence": round(intent.confidence, 4) if intent else None,
                "blocked_reason": result.blocked_reason,
            })

    moderator = OutputModerator()
    output_rows: list[dict] = []
    for item in payloads["output"]:
        text = expand(item["text"])
        for level in LEVELS:
            moderated = moderator.moderate(text, level)
            output_rows.append({
                "text_id": item["id"],
                "level": level,
                "moderated": moderated,
                "length": len(moderated),
            })

    return {
        "_comment": (
            "Generated by scripts/record_defense_golden.py. Do not hand-edit. "
            "Regenerate only when a defense change is intended, and review the diff."
        ),
        "thresholds": {
            "l1_confidence_threshold": settings.defense.l1_confidence_threshold,
            "l2_confidence_threshold": settings.defense.l2_confidence_threshold,
            "confidence_full_match_count": CONFIDENCE_FULL_MATCH_COUNT,
        },
        "input": input_rows,
        "output": output_rows,
    }


def main() -> None:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    baseline = asyncio.run(record())
    BASELINE_PATH.write_text(json.dumps(baseline, indent=2, sort_keys=True) + "\n")
    print(
        f"Wrote {BASELINE_PATH.relative_to(_ROOT)}: "
        f"{len(baseline['input'])} input rows, {len(baseline['output'])} output rows"
    )


if __name__ == "__main__":
    main()
